[package]
name = "rust-http-proxy"
version = "0.1.0"
authors = ["Sean Burton <sean.burton@thalesesecurity.com>"]
edition = "2018"

[dependencies]
log = "^0.4.8"
tokio = "=0.2.0-alpha.4"

[dev-dependencies]
env_logger = "^0.6.2"
